parameters:
  # Number of states to be integrated by RK4
  number_of_states: 10

  # Length of the array vector that will be exported 
  size_DATA: 50

  # **Translational** PID parameters 
  KP_tran: [77,84,35]
  KD_tran: [34,29,6]
  KI_tran: [129,53,53]

  # **Rotational** PID parameters
  KP_rot: [100,100,50]
  KD_rot: [50,50,50]
  KI_rot: [20,20,10]
  
  # ----------------------------------------------------------------
  #                   Safety Mechanism Parameters
  # ----------------------------------------------------------------
  use_safety_mechanism: True
  
  # Mu - sphere intersection
  sphereEpsilon: !!float 1e-2
  maximumThrust: 85 # [N] 85
  
  # Mu - elliptic cone intersection
  EllipticConeEpsilon: !!float 1e-2
  maximumRollAngle: 60 # [rad]
  maximumPitchAngle: 60 # [rad]
  
  # Mu - plane intersection
  planeEpsilon: !!float 1e-2
  alphaPlane: 0.6 # [-] coefficient for setting the 'height' of the bottom plane. Must be >0 and <1.